spring:
  application:
    name: spring-data-jpa-course
  datasource:
    url: jdbc:mysql://localhost:3306/jpa-course
    username: tom
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      auto-commit: false #delay database acquisition
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate #control how Hibernate manages db schema at startup - only check that the schema matches entities
    properties:
      hibernate:
        format_sql: true
#        connection:
#          provider_disables_autocommit: true
  flyway:
    enabled: true #run flyway on startup
    locations: classpath:db/migration
    validate-on-migrate: true #validate checksum of applied migrations - fails if files were changed after being applied
  main:
    banner-mode: off
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      stop:
        command: stop
      start:
        command: up

server:
  port: 8080

logging:
  pattern:
    console: "%green(%d{yyyy-MM-dd HH:mm:ss.SSS}) %blue(%-5level) %magenta(${PID:- }) --- %red([%15.15thread]) %yellow(%-40.40logger{39}): %msg%n%wEx"
  level:
    root: info
    org.tommap.springdatajpacourse: debug
    org.hibernate.orm.jdbc.bind: trace
    com.zaxxer.hikari: trace
    com.zaxxer.hikari.pool.HikariPool: trace
    com.zaxxer.hikari.pool.PoolBase: trace
    org.hibernate.engine.jdbc.connections: trace
    org.hibernate.resource.jdbc: trace